Fix for NestedScrollView issues
saket/InboxRecyclerView pull request #21
Opened 2018-12-23 13:45 UTC by andb3

The fix works for any amount of items above the content, though with no support for items below. 

It can be set using `InboxRecyclerView.setNested()`

2019-02-25 18:38 UTC, SubhrajyotiSen commented on sample/src/main/java/me/saket/inboxrecyclerview/sample/inbox/InboxActivity.kt
> +import timber.log.Timber
You can remove this import right?

2019-02-25 18:38 UTC, SubhrajyotiSen commented on sample/build.gradle
> +  implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
ConstraintLayout isn't being used anywhere

2019-07-30 21:38 UTC, afollestad requested changes

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/InboxRecyclerView.kt
> +    if(isNested) {
You should format this file, there's some oddities with indentation and such

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/InboxRecyclerView.kt
> +        top + itemView.top ,
Extra space

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/InboxRecyclerView.kt
> +
Unnecessary line breaks

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/InboxRecyclerView.kt
> +
Unnecessary line breaks

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/InboxRecyclerView.kt
> +      val offset = if(isNested) (parent.parent as NestedScrollView).scrollY else 0
Odd indentation

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/InboxRecyclerView.kt
> +  fun setNested(boolean: Boolean = true){
This parameter should have a more useful and descriptive name.

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/animation/NestedExpandAnimator.kt
> +        if(nest !is NestedScrollView){
You should use Kotlin's `check`, instead. 

```kotlin
check (nest is NestedScrollView) {
   "Exception message here"
}
```

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/animation/NestedExpandAnimator.kt
> +
Unnecessary line breaks

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/animation/NestedExpandAnimator.kt
> +        if(page.isExpandedOrExpanding){
This if and else has odd formatting

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/animation/NestedExpandAnimator.kt
> +        anchorView?.apply {
You do a null check on this above, so the contents of this apply should be moved in there instead

2019-07-30 21:38 UTC, afollestad commented on inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/animation/NestedExpandAnimator.kt
> +        nest.getChildAt(0).apply {
The use of `apply` is unnecessary here

2019-07-30 21:38 UTC, afollestad commented on sample/build.gradle
> +  implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
+1

2019-07-30 21:38 UTC, afollestad commented on sample/src/main/java/me/saket/inboxrecyclerview/sample/inbox/InboxActivity.kt
> +import timber.log.Timber
+1

2021-04-01 06:48 UTC, saket commented
Thanks for contributing this @andb3. We weren't able to merge this in, but I managed to write my own implementation as part of v3.0: https://github.com/saket/InboxRecyclerView/releases/tag/v3.0.

2021-04-01 06:48 UTC, closed without merging